# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a274004351ed03202d14d19c5477e94"
name = "sonnh-capstone-project"
application_url = "https://justness-keep-plaza.ngrok-free.dev"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://justness-keep-plaza.ngrok-free.dev/auth/callback" ]
